name = "ws2812"
version = 5

[device]
family = "GW5AST-138B"
part = "GW5AST-LV138FPG676AC1/I0"

[hdl]
standard = "sysv2017"
top = "top"

[files]
verilog = [
    "../../cores/ws2812/ws2812.sv",
    "top.sv",
]
cst = "phy.cst"
sdc = "timings.sdc"

[programmer]
fs = "impl/pnr/project.fs"

preset.sram = { op = "2" }
preset.spi = { op = "53" }
